### ISSUE TITLE
logstash-versjon?

### ISSUE THREAD

**Issue by omega** [mbertani/elk-workshop#8]
Skal på workshop i morgen, og prøvde å følge instruksjonene, men endte opp med logstash version 2.4, mens `verify-logstash.sh` spør etter 2.3.4?

**Comment by Sardtok** [comment]
Vi hadde egentlig tenkt at vi skulle droppe det steget i workshoppen siden vi skal ta i bruk VM, så den har unsluppet noen oppdateringer. Skal legge inn riktig versjonsnummer tilsvarende de oppdaterte setup-skriptene.
